spring.application.name=delivery-service
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/delivery_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:proba123}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SHOW_SQL:false}

management.endpoints.web.exposure.include=health,info,metrics

clients.auth.url=${AUTH_SERVICE_URL:http://localhost:8081}
clients.order.url=${ORDER_SERVICE_URL:http://localhost:8086}
